const {
  AndroidConfig,
  withAndroidManifest,
  withAppBuildGradle,
} = require('expo/config-plugins');

const META_DATA_NAME = 'com.google.android.geo.API_KEY';
const PLACEHOLDER = '${googleMapsApiKey}';
const GRADLE_MARKER = '// @generated by withAndroidGoogleMapsEnv';

const gradleConfiguration = `${GRADLE_MARKER}
def readGoogleMapsApiKey = {
    def configuredKey = findProperty('EXPO_PUBLIC_GOOGLE_MAPS_API_KEY') ?: System.getenv('EXPO_PUBLIC_GOOGLE_MAPS_API_KEY')
    if (configuredKey) return configuredKey

    for (envFile in [file("../../.env.production"), file("../../.env")]) {
        if (!envFile.exists()) continue
        def line = envFile.readLines().find { it ==~ /^\\s*EXPO_PUBLIC_GOOGLE_MAPS_API_KEY\\s*=.*/ }
        if (line) return line.split("=", 2)[1].trim().replaceAll(/^["']|["']$/, "")
    }

    return ""
}
def googleMapsApiKey = readGoogleMapsApiKey()
`;

function withGoogleMapsManifest(config) {
  return withAndroidManifest(config, (configWithManifest) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      configWithManifest.modResults
    );
    application['meta-data'] = application['meta-data'] || [];

    const existing = application['meta-data'].find(
      (item) => item.$?.['android:name'] === META_DATA_NAME
    );
    const entry = existing || { $: { 'android:name': META_DATA_NAME } };
    entry.$['android:value'] = PLACEHOLDER;

    if (!existing) application['meta-data'].push(entry);
    return configWithManifest;
  });
}

function withGoogleMapsGradle(config) {
  return withAppBuildGradle(config, (configWithGradle) => {
    if (configWithGradle.modResults.language !== 'groovy') {
      throw new Error('withAndroidGoogleMapsEnv requires a Groovy app/build.gradle');
    }

    let contents = configWithGradle.modResults.contents;
    if (!contents.includes(GRADLE_MARKER)) {
      contents = contents.replace('\nandroid {', `\n${gradleConfiguration}\nandroid {`);
    }
    contents = contents.replace(
      /(defaultConfig\s*\{)/,
      '$1\n        manifestPlaceholders = [googleMapsApiKey: googleMapsApiKey]'
    );
    configWithGradle.modResults.contents = contents;
    return configWithGradle;
  });
}

module.exports = function withAndroidGoogleMapsEnv(config) {
  return withGoogleMapsGradle(withGoogleMapsManifest(config));
};
