import { StyleSheet } from "react-native";
import { scale } from "react-native-size-matters";
import { colors, spacing, shadows, borderRadius } from "./theme";

const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.xl,
    alignItems: "center",
    paddingVertical: spacing.lg,
    marginHorizontal: spacing.sm,
    ...shadows.primaryGlow,
  },
  buttonText: {
    color: colors.surface,
    fontSize: scale(16),
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  input: {
    flex: 1,
    width: scale(318),
    height: scale(50),
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    marginHorizontal: spacing.sm,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.surface,
    fontSize: scale(15),
    color: colors.textPrimary,
    ...shadows.sm,
  },
  row: {
    flexDirection: "row",
    marginBottom: spacing.xl,
  },
  headerText: {
    fontSize: scale(18),
    alignSelf: "center",
    color: colors.textPrimary,
    fontWeight: "800",
    marginBottom: spacing.sm,
    letterSpacing: 0.5,
  },
  divider: {
    borderBottomColor: colors.borderLight,
    borderWidth: scale(0.5),
    width: scale(300),
    marginRight: scale(50),
    marginVertical: spacing.lg,
  },
  circle: {
    width: scale(35),
    height: scale(35),
    borderRadius: scale(75),
    borderColor: colors.primary,
    borderWidth: scale(2),
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginHorizontal: scale(18),
    marginTop: spacing.xl,
    ...shadows.primaryGlow,
  },
});

const mapScreenStyles = StyleSheet.create({
  map: {
    flex: 1,
  },
  details: {
    width: scale(40),
    height: scale(40),
    position: "absolute",
    borderRadius: borderRadius.sm,
    backgroundColor: colors.surface,
    top: scale(35),
    alignItems: "center",
    justifyContent: "center",
    left: spacing.xl,
    ...shadows.md,
  },
  back: {
    width: scale(30),
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    bottom: scale(260),
    alignItems: "center",
    justifyContent: "center",
    left: spacing.xl,
    ...shadows.md,
  },
  backDetails: {
    width: scale(30),
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    bottom: scale(530),
    alignItems: "center",
    justifyContent: "center",
    left: spacing.xl,
    ...shadows.md,
  },
  svgContainer: {
    width: scale(318),
    height: scale(50),
    borderRadius: borderRadius.sm,
    borderWidth: scale(4),
    borderColor: colors.primary,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: spacing.lg,
    paddingHorizontal: spacing.lg,
    marginVertical: spacing.sm,
  },
});

export { commonStyles, mapScreenStyles }; 